# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-epitopeprediction-1.2.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7.15 #dont upgrade, FRED2 needs python 2.7 for now
  - multiqc=1.6 #cant upgrade due to Python2 fix
  - snpsift=4.3.1t
  - csvtk=0.19.1
  - fred2=2.0.7
  - mhcflurry=1.4.3
  - mhcnuggets=2.3.2
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::r-markdown=1.1
  - conda-forge::tcsh=6.22.03 # netmhc dependency
  - bioconda::perl-env=1.04 # netmhc dependency
  - gawk=5.1.0 # netmhc dependency
